theme: jekyll-theme-midnight
title: <link rel="Initials Logo" href="Initials_Logo.png" type="image/x-icon" /><span style="color:#ffcc00">Welcome to Scott Courchaine's Homepage!</span>
description: <span style="color:#b6b6b6">This is for my SNHU projects directed towards my capstone.</span>
